### PR TITLE
Show the IP address for connecting the client device

### LINKED ISSUE #19: As a user, I'm shown how to connect to the host machine, so that I can share files.
## Acceptance Criteria
- [x] The address to connect to is displayed.

## Notes/TODO
- Only works when connected to an external router ie. not when host is hotspot
- need to pretify

## Front end
- [x] Display the ipaddress and port the client should connect to

## Back end
- [x] get the ipaddress and port the host serves

### PR DESCRIPTION
**Pull request by at527**
This PR allows the ipaddress to be shown so that the client device can connect to the host machine.
It provides this in an instruction list. No changes are made to the gui aside from the ipaddress and instructions.

Here's how it looks.
image

### CODE REVIEW

**Review by dougyuan — APPROVED** [review]
LGTM!

**Comment by ethwu** [comment]
Could we make the address a hyperlink? Not that it'd be very useful, but people are used to seeing [glowy blue text](#) and associating it with being a URL. Either that or putting it in \<angle brackets\> (Or ⟨chevrons⟩, if you wanna be fancy about it).

**Comment by at527** [comment]
> Could we make the address a hyperlink? Not that it'd be very useful, but people are used to seeing [glowy blue text](#) and associating it with being a URL. Either that or putting it in <angle brackets> (Or ⟨chevrons⟩, if you wanna be fancy about it).

Yeah I can my the address more prominent. I was wary of making the address a link because I didn't want users to click on it, opening the link on the host machine instead of the client device. Will play around with it.

**Review by zmondin — APPROVED** [review]
Worked on my machine. We should pass the port number through at some point so it's not hard coded like you said but other than that it looks good to me!

**Review by kphamm — APPROVED** [review]
yup works for me

**Comment by ethwu** [comment]
Looks good, merging!

**Pull request merged**
