### PR TITLE
Improve Desktop QT gui, add send/receive buttons

### LINKED ISSUE #36: As a user, the qt gui is more intuitive to use, so that I can use the program more easily.
## Acceptance Criteria
- [x] Instructions for connecting
- [x] Button for selecting files to send
- [x] Button for viewing files received

### PR DESCRIPTION
**Pull request by at527**
This PR makes changes to the layout of the desktop QT gui. 
Currently the buttons do not work, and this only adds the gui elements.

Here's how it looks.
image

### CODE REVIEW

**Review by dougyuan — APPROVED** [review]
LGTM! 

n.b. `netifaces` should be listed as a new dependency.

**Comment by ethwu** [comment]
Make sure to `pip freeze > requirements.txt` so that `netifaces` is installed automatically; I think the button names might be a bit long. Maybe _Send Files_ and _Open Inbox_ or _Open Received_?

I still think it might be better for the server to be open by default, since in 99% of cases you're going to open the app and press the _Open Connections_ button immediately, then close the server immediately before closing the app. What do you guys think?

**Comment by at527** [comment]
> Make sure to `pip freeze > requirements.txt` so that `netifaces` is installed automatically; I think the button names might be a bit long. Maybe _Send Files_ and _Open Inbox_ or _Open Received_?
> 
> I still think it might be better for the server to be open by default, since in 99% of cases you're going to open the app and press the _Open Connections_ button immediately, then close the server immediately before closing the app. What do you guys think?

Removing the need for starting is a good idea, and the functionality especially unnecessary when we have some security. The netifaces is part of the ip address branch so I've changed it there.

**Review by zmondin — COMMENTED** [review]
I think using an inbox/outbox theme for those buttons will be a lot easier and cleaner for the user.  Otherwise, it works as intended and I like the addition of the "Done Transferring" button.

**Review by kphamm — CHANGES_REQUESTED** [review]
the code works but we need to revert back to sending files to the downloads folder and i definitely agree that the button names are too long LOL

**Pull request merged**
